# This workflow to run the test suite for CWInPy - uses Docker images for bilby

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.8
            container: containers.ligo.org/lscsoft/bilby/v2-bilby-python38
          - python-version: 3.9
            container: containers.ligo.org/lscsoft/bilby/v2-bilby-python39

    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install CWInPy
      run: |
        # install libstempo
        conda install -c conda-forge libstempo
        # install in editable mode due to Cython files https://stackoverflow.com/a/48331262/1862861
        pip install -e .[test]
    - name: Run test suite
      run: |
        # disable numba jit for code coverage (see https://stackoverflow.com/a/26894553/1862861)
        export NUMBA_DISABLE_JIT=1
        pytest --cov=cwinpy
    - name: Run codecov
      run: |
        codecov
